CREATE DATABASE IF NOT EXISTS CS341;
use CS341;

CREATE TABLE IF NOT EXISTS User (
  FirstName NVARCHAR(12) NOT NULL,
  LastName NVARCHAR(12) NOT NULL,
  Email NVARCHAR(25) PRIMARY KEY NOT NULL,
  Password VARCHAR(256) NOT NULL,
  PhoneNum LONG NOT NULL,
  Active INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ServiceProvider (
  FirstName NVARCHAR(12) NOT NULL,
  LastName NVARCHAR(12) NOT NULL,
  Email NVARCHAR(25) PRIMARY KEY NOT NULL,
  Password VARCHAR(256) NOT NULL,
  PhoneNum LONG NOT NULL,
  Qualification NVARCHAR(120) NOT NULL,
  YearGraduated INT NOT NULL,
  Type NVARCHAR(8) NOT NULL,
  Active INT NOT NULL
  );

CREATE TABLE IF NOT EXISTS Admin (
  UserId NVARCHAR(12) PRIMARY KEY NOT NULL,
  Password VARCHAR(256) NOT NULL
);

CREATE TABLE IF NOT EXISTS Appointment (
  ApptId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  Description NVARCHAR(120) NOT NULL,
  Date DATE NOT NULL,
  Time TIME NOT NULL,
  Type NVARCHAR(8) NOT NULL,
  Booked INT NOT NULL,
  Canceled INT,
  Notified INT,
  UserEmail NVARCHAR(25),
  SPEmail NVARCHAR(25),
  CONSTRAINT FK_User_email FOREIGN KEY (UserEmail) REFERENCES User(Email),
  CONSTRAINT FK_SP_email FOREIGN KEY (SPEmail) REFERENCES ServiceProvider(Email)
);

-- jdbc:mysql://127.0.0.1:3306/?user=root