CREATE DATABASE IF NOT EXISTS CS341;
use CS341;

CREATE TABLE IF NOT EXISTS Appointment (
  ApptId INT PRIMARY KEY NOT NULL,
  Type NVARCHAR(8) NOT NULL,
  Time TIME NOT NULL,
  Day NVARCHAR(10) NOT NULL,
  Length INT NOT NULL,
  Booked NVARCHAR(3) NULL
);

CREATE TABLE IF NOT EXISTS User (
  FirstName NVARCHAR(12) NOT NULL,
  LastName NVARCHAR(12) NOT NULL,
  Email NVARCHAR(25) PRIMARY KEY NOT NULL,
  Password VARCHAR(255) NOT NULL,
  PhoneNum VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS ServiceProvider (
  FirstName NVARCHAR(12) NOT NULL,
  LastName NVARCHAR(12) NOT NULL,
  Email NVARCHAR(25) PRIMARY KEY NOT NULL,
  Password VARCHAR(255) NOT NULL,
  PhoneNum INT NOT NULL,
  StartTime INT NOT NULL,
  StopTime INT NOT NULL,
  Qualification NVARCHAR(120) NOT NULL,
  YearGraduated INT NOT NULL,
  Type NVARCHAR(8) NOT NULL
  );

CREATE TABLE IF NOT EXISTS Admin (
  UserId NVARCHAR(12) PRIMARY KEY NOT NULL,
  Password VARCHAR(255) NOT NULL
  );
